### ISSUE TITLE
一点小小的卑微的问题

### ISSUE THREAD

**Issue by ForeUP** [chenjunlinabc/concise_orange#1]
老哥可以告诉我一下换站点的logo的位置吗，官方默认模板挺简单，但是配色ui略微有点简陋，这么简单的主题正适合我 @chenjunlinabc

**Comment by chenjunlinabc** [comment]
如果是指左上角的logo的话，这个是通过<?php $this->options->title() ?>获取typecho后台设置的站点名称，当然也可以手动修改，改成其他图片都是可以的，在header.php的第47行
